export const FOREX_DEAL_ACTION_TYPE = {
  NEW_FOREX_DEAL: "NEW_FOREX_DEAL",
  FETCH_FOREX_DEALS_PENDING: "FETCH_FOREX_DEALS_PENDING",
  FETCH_FOREX_DEALS_SUCCESS: "FETCH_FOREX_DEALS_SUCCESS",
  SUBMIT_FOREX_DEAL_PENDING: "SUBMIT_FOREX_DEAL_PENDING",
  SUBMIT_FOREX_DEAL_SUCCESS: "SUBMIT_FOREX_DEAL_SUCCESS",
};

export const FOREX_RATE_ACTION_TYPE = {
  BOOK_FOREX_RATE_PENDING: "BOOK_FOREX_RATE_PENDING",
  BOOK_FOREX_RATE_SUCCESS: "BOOK_FOREX_RATE_SUCCESS",
  FETCH_FOREX_RATES_PENDING: "FETCH_FOREX_RATES_PENDING",
  FETCH_FOREX_RATES_SUCCESS: "FETCH_FOREX_RATES_SUCCESS",
  FETCH_FOREX_BASE_CURRENCIES_PENDING: "FETCH_FOREX_BASE_CURRENCIES_PENDING",
  FETCH_FOREX_BASE_CURRENCIES_SUCCESS: "FETCH_FOREX_BASE_CURRENCIES_SUCCESS",
};

export const LOGIN_SESSION_ACTION_TYPE = {
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_PROVIDER_PENDING: "LOGIN_PROVIDER_PENDING",
  LOGIN_PROVIDER_SUCCESS: "LOGIN_PROVIDER_SUCCESS",
  LOGIN_CANCEL: "LOGIN_CANCEL",
  LOGIN_PROVIDER_FAIL: "LOGIN_PROVIDER_FAIL",
  LOGOUT_PENDING: "LOGOUT_PENDING",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const CONFIG_ACTION_TYPE = {
  INITIALIZE_PENDING: "INITIALIZE_PENDING",
  INITIALIZE_SUCCESS: "INITIALIZE_SUCCESS",
};

export const UI_STATE_ACTION_TYPE = {
  DISMSS_TOAST: "DISMISS_TOAST",
};
